---
- name: Uninstall old versions
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Update apt
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add and apt
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable'

- name: Finger print
  apt_key:
    id: 0EBFCD88
    state: present

- name: Update apt
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce
    state: latest
  notify: enable docker

- name: Append user ubuntu to group docker
  user:
    name: ubuntu
    groups: docker
    append: yes
